# docker-compose -f prometheus-grafana.yml down; docker-compose -f prometheus-grafana.yml up
version: '2.1'

services:
    prometheus:
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes:
            - ./prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
    grafana:
        image: grafana/grafana
        ports:
          - "3010:3000"
