global:
    scrape_interval:     10s
    evaluation_interval: 10s

scrape_configs:
 - job_name: 'prometheus'
   metrics_path: '/metrics'
   static_configs:
   - targets: ['127.0.0.1:9090']
 - job_name: 'local-burrow-instance'
   metrics_path: '/metrics'
   static_configs:
   - targets: ['docker.for.mac.localhost:8800']
